name: "Cleanup AWS Test Account"

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
    
jobs:
  cleanup_tests_account:
    name: Cleanup Test Account
    environment: smooth-infra-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::994884320581:role/GitHubCICD
          role-session-name: JOB-${{ github.job }}-ID-${{ github.run_number }}-RUN-${{ github.run_attempt }}
          aws-region: ${{ vars.AWS_REGION }}
        
      - uses: actions/cache@v2
        id: aws-nuke
        with: 
          path: aws-nuke  
        
      - name: Download AWS Nuke
        if: steps.aws-nuke.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-arm64.tar.gz | tar -xz -C ${{ github.workspace }} && \
            mv ${{ github.workspace }}/aws-nuke-v2.21.2-linux-arm64/aws-nuke ${{ github.workspace }} && \
            rm -rf /aws-nuke-v2.21.2-linux-arm64 && \
            chmod +x aws-nuke
            
      - name: Run AWS Nuke
        if: steps.aws-nuke.outputs.cache-hit == 'true'
        run: |
          aws-nuke -c build-aws_nuke.yml --profile smooth-infra-tests
